[default.extend-words]
muc = "muc" # For Munich location code
tyo = "tyo" # For Tokyo location code
Hashi = "Hashi"
HashiCorp = "HashiCorp"
mavrickrishi = "mavrickrishi" # Username
mavrick = "mavrick" # Username
inh = "inh" # Option in setpriv command
exportfs = "exportfs" # nfs related binary
melmathari = "melmathari" # Username
fsn1 = "fsn1" # Hetzner Falkenstein datacenter code
nbg1 = "nbg1" # Hetzner Nuremberg datacenter code
hel1 = "hel1" # Hetzner Helsinki datacenter code
hel = "hel"   # Hetzner Helsinki short code
hcloud = "hcloud" # Hetzner Cloud CLI/API
vcpus = "vcpus" # Virtual CPUs

[files]
extend-exclude = ["registry/coder/templates/aws-devcontainer/architecture.svg"] #False positive